---
name: Issue (Bug Report)
description: File a bug report to help us improve.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["DSA"]
assignees:
  - github-username
body:
  - type: markdown
    id: appreciation
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: 📋 Checklist
      description: Make sure to add all the information needed to understand the bug so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.
      options:
        - label: Can you reproduce the problem in safe mode?
          required: false
        - label: Are you running the latest version?
          required: false
        - label: Did you check the debugging guide?
          required: false
        - label: Are you reporting to the correct repository?
          required: false
        - label: Did you perform a cursory search?
        - label: Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.
        - label: Have an idea for a feature? Post the feature request on Product Pains. It has a voting system to surface the important issues. GitHub issues should only be used for bugs.
        - label: Provide a minimal code snippet example that reproduces the bug.
        - label: Provide screenshots where appropriate
        - label: What's the version of compiler you're using?
        - label: Does this occur on iOS, Android or both?
        - label: Are you using Mac, Linux or Windows?
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: terminal
    attributes:
      label: What terminal are you seeing the problem on?
      multiple: true
      options:
        - Terminal
        - iTerm2
        - Kitty
        - PuTTY
        - Other (Please specify in description)
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/TheScienceUniverse/DSA/blob/master/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
---
